### ISSUE TITLE
The actual projection resolution of the projector

### ISSUE THREAD

**Issue by Quma233** [uzh-rpg/ESL#3]
Regarding the projector SONY MP- CL1A used in the hardware system, I found that the resolution mentioned in the article and the code (1920x1080) is not the same as the resolution labeled in the projector user manual (1920x720). So, what is the actual projection size of the projector? This is very important as it directly affects the stereo matching process.

Here is the link to the projector user manual:
https://www.sony.com/electronics/support/res/manuals/C261/C2610191M.pdf

**Comment by Manasi94** [comment]
Although the documentation mentions resolution of 1920x720, in practice, we were able to set the resolution to 1920x1080 when connected with an hdmi cable
