### ISSUE TITLE
How to generate book_duck.gif?

### ISSUE THREAD

**Issue by zbxmchgf** [uzh-rpg/ESL#4]
Hi @Manasi94 , thanks for your inspiring work! Could you please provide some details about how to generate  book_duck.gif?
![image](https://github.com/uzh-rpg/ESL/assets/67113033/4b218c8d-cc20-43f2-8bfa-152044c176dd)

**Comment by Manasi94** [comment]
This gif was generated using the Prophesee 2.0 visualizer of '.dat' file. 
In the visualizer there is an option to slow down the dat file. After the desired speed was achieved, an off the shelf screen recorder was used to record a gif.

**Comment by dhawals1939** [comment]
Hi, when downloading the data. I could only see ".raw" files. Is it the same as ".dat" files.?
